esphome:
  name: curly_eureka_1
  platform: ESP8266
  board: d1_mini
  includes:
  - d1_mini_motor.h


wifi:
  ssid: !secret esp_wifi_ssid
  password: !secret esp_wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esp_backup_ssid
    password: !secret esp_backup_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esp_api_password

ota:
  password: !secret esp_ota_password

# ===================================
# TNS addtions over ther base wizard

# This uses the modified slow_pwm component that has an optiona; PIN_B that is
# anti-phase to the mandatory pin.
output:
  - platform: slow_pwm
    pin:
      number: D5
      mode: OUTPUT
    pin_b:
      number: D6
      mode: OUTPUT
    id: my_slow_pwm
    period: 1s
  

# Using the switch component to drive both the single LED and the slow_pwm.
switch:
  - platform: output
    output: my_slow_pwm
    name: "Office Strobe Slow"

  - platform: gpio
    name: "Office Room Airconditioner"
    pin:
      number: D0
      mode: OUTPUT
  # Custom Wimos v1 Motor controller
  - platform: custom
    lambda: |-
      auto my_lights = new WMotorCustomComponent(0x30, _MOTOR_A, 1000);
      App.register_component(my_lights);
      return {my_lights};
    switches:
      name: "Christmas LEDS"
  - platform: custom
    lambda: |-
      auto b_lights = new WMotorCustomComponent(0x30, _MOTOR_B, 1000);
      App.register_component(b_lights);
      return {b_lights};
    switches:
      name: "Christmas LEDS - B"
i2c:
  sda: 4
  scl: 5
  scan: True
  id: bus_a

sensor:
  - platform: bme280
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
      id: bmetemp
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
      id: bmerh
    address: 0x76
    update_interval: 60s

display:
  - platform: lcd_pcf8574
    dimensions: 16x2
    address: 0x27
    id: tnsdisplay
    # Apparent temperature from https://planetcalc.com/2089/
    lambda: |-
      float app_temp;
      app_temp = id(bmetemp).state + 0.348 * (id(bmerh).state/100)*6.105*exp((17.27*id(bmetemp).state)/(237.7+id(bmetemp).state)) - 4.25;
      it.printf(0,0,"Temp:%.1f~%.1fC", id(bmetemp).state, app_temp);
      it.strftime(0,1,"Time:%H:%M", id(tns_time).now());

# (Optional) For displaying time:
time:
- platform: sntp
  id: tns_time